[package]
name = "advent-of-code-2025"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
grid = "1.0.0"
itertools = "0.14.0"
strum = { version = "0.27", features = ["derive"] }
thiserror = "2.0.17"

[dev-dependencies]
pretty_assertions = "1.4.1"
